sources:
  - id: S-001
    name: White Rabbit Black Ink article
    url: https://milwaukiereview.com/2017/09/13/white-rabbit-black-ink-opens-doors-on-main-street/

  - id: S-002
    name: New Kwality Cafe matchbook
    url: https://americandiners.blogspot.com/2015/

  - id: S-003
    name: Larry's Kwality Cafe matchcover
    url: https://www.matchcovercollector.com/matchcover-category/food/food-rest/food-rest-cafe/page/138/

  - id: S-004
    name: 505 Tavern / Thirsty Duck article
    url: https://milwaukiereview.com/2017/08/18/newest-old-bar-in-clackamas-county-reopens-in-oregon-city/

