from pathlib import Path

dates=[('1916-11-03','3 November 1916','november03','S-360','E-333'),('1916-11-10','10 November 1916','november10','S-361','E-334'),('1916-11-17','17 November 1916','november17','S-362','E-335')]
for date,label,slug,sid,eid in dates:
    p=Path(f'evidence/source-captures/1916-enterprise-{slug}-visual-review-2026-09-13.md')
    if p.exists(): raise SystemExit(f'{p} already exists')
    p.write_text(f'''# Oregon City Enterprise — {label} — complete issue visual review\n\n**Status:** VISUALLY VERIFIED — **8/8 genuine weekly pages inspected** on 13 September 2026.  \n**Source:** *Oregon City Enterprise*, {label}, edition 1, University of Oregon Historic Oregon Newspapers, LCCN `sn00063700`.  \n**Canonical issue:** https://oregonnews.uoregon.edu/lccn/sn00063700/{date}/ed-1/  \n**Repository originals:** `newspapers/oregon-city-enterprise/1916/{date}/`.\n\n## Retrieval and review method\n\nThe repository fetch workflow preserved the eight valid original page PDFs plus a fetch manifest. Every preserved PDF was rendered to a faithful page image and each page was individually visually inspected at readable scale. OCR/text extraction was discovery/navigation only and did not substitute for scan review.\n\n## Findings\n\nNo inspected page directly assigns an occupant, proprietor, business owner, property owner, tenant, licensee, trade name, sale/transfer, construction, demolition, rebuilding, closure, vacancy, fire, or move to **501, 503, 505, 505½, or 507 Main Street**. Recurring non-target Main Street advertising and professional-directory controls were visually checked, together with real-estate-transfer material where printed; none supplies a source-explicit target-block event.\n\n## Cross-record propagation audit\n\nThis issue adds annual visual-coverage evidence only. It does **not** establish a new target occupant, business, ownership, tenancy, licensing, or building fact. No target timeline/building/business/person fact is manufactured from the no-hit.\n\n## Evidentiary limits\n\n- No source-explicit target-premises event was found in the complete eight-page issue.\n- Repeated Tenth/Main and Fourth–Fifth/Main references remain non-target geographic controls only.\n- No-hit language is bounded issue coverage and is not evidence of vacancy, non-use, demolition, closure, or non-ownership.\n''')

src=Path('evidence/source-register.md'); s=src.read_text()
for sid in ('S-360','S-361','S-362'):
    if f'## {sid} —' in s: raise SystemExit(f'{sid} already allocated')
s += '''\n\n## S-360 — Oregon City Enterprise, 3 November 1916, complete issue visual review\nType: Primary newspaper page scans; visually verified **8/8 pages**  \nDate: 3 November 1916  \nURL: https://oregonnews.uoregon.edu/lccn/sn00063700/1916-11-03/ed-1/  \nRepository capture: `evidence/source-captures/1916-enterprise-november03-visual-review-2026-09-13.md`  \nRelated evidence: `E-333`.  \nNotes: Complete issue visually reviewed; recurring non-target Main Street controls and transfer material checked; no source-explicit target-premises event.\n\n## S-361 — Oregon City Enterprise, 10 November 1916, complete issue visual review\nType: Primary newspaper page scans; visually verified **8/8 pages**  \nDate: 10 November 1916  \nURL: https://oregonnews.uoregon.edu/lccn/sn00063700/1916-11-10/ed-1/  \nRepository capture: `evidence/source-captures/1916-enterprise-november10-visual-review-2026-09-13.md`  \nRelated evidence: `E-334`.  \nNotes: Complete issue visually reviewed; recurring non-target Main Street controls and transfer material checked; no source-explicit target-premises event.\n\n## S-362 — Oregon City Enterprise, 17 November 1916, complete issue visual review\nType: Primary newspaper page scans; visually verified **8/8 pages**  \nDate: 17 November 1916  \nURL: https://oregonnews.uoregon.edu/lccn/sn00063700/1916-11-17/ed-1/  \nRepository capture: `evidence/source-captures/1916-enterprise-november17-visual-review-2026-09-13.md`  \nRelated evidence: `E-335`.  \nNotes: Complete issue visually reviewed; recurring non-target Main Street controls and transfer material checked; no source-explicit target-premises event.\n'''; src.write_text(s)

ev=Path('evidence/evidence-register.md'); s=ev.read_text()
for eid in ('E-333','E-334','E-335'):
    if f'## {eid} —' in s: raise SystemExit(f'{eid} already allocated')
s += '''\n\n## E-333 — 3 November 1916 Enterprise complete visual review\nType: Primary newspaper visual evidence / annual issue-level coverage  \nClaims: All **8/8** page scans were visually inspected. Recurring non-target Main Street controls and printed transfer material were checked. No inspected page directly supplies a target-premises event.  \nSource: `S-360`.  \nConfidence: Very High for visual coverage; no-hit is bounded issue coverage only.\n\n## E-334 — 10 November 1916 Enterprise complete visual review\nType: Primary newspaper visual evidence / annual issue-level coverage  \nClaims: All **8/8** page scans were visually inspected. Recurring non-target Main Street controls and printed transfer material were checked. No inspected page directly supplies a target-premises event.  \nSource: `S-361`.  \nConfidence: Very High for visual coverage; no-hit is bounded issue coverage only.\n\n## E-335 — 17 November 1916 Enterprise complete visual review\nType: Primary newspaper visual evidence / annual issue-level coverage  \nClaims: All **8/8** page scans were visually inspected. Recurring non-target Main Street controls and printed transfer material were checked. No inspected page directly supplies a target-premises event.  \nSource: `S-362`.  \nConfidence: Very High for visual coverage; no-hit is bounded issue coverage only.\n'''; ev.write_text(s)

srcy=Path('database/sources.yml'); s=srcy.read_text()
for sid in ('S-360','S-361','S-362'):
    if f'  - id: {sid}' in s: raise SystemExit(f'{sid} already allocated YAML')
s += '''\n\n  - id: S-360\n    name: "Oregon City Enterprise, 3 November 1916, complete issue visual review"\n    url: "https://oregonnews.uoregon.edu/lccn/sn00063700/1916-11-03/ed-1/"\n    type: "Primary newspaper page scans; visually verified 8/8 pages"\n    date: "1916-11-03"\n    repository_file: "evidence/source-captures/1916-enterprise-november03-visual-review-2026-09-13.md"\n    related_evidence: [E-333]\n  - id: S-361\n    name: "Oregon City Enterprise, 10 November 1916, complete issue visual review"\n    url: "https://oregonnews.uoregon.edu/lccn/sn00063700/1916-11-10/ed-1/"\n    type: "Primary newspaper page scans; visually verified 8/8 pages"\n    date: "1916-11-10"\n    repository_file: "evidence/source-captures/1916-enterprise-november10-visual-review-2026-09-13.md"\n    related_evidence: [E-334]\n  - id: S-362\n    name: "Oregon City Enterprise, 17 November 1916, complete issue visual review"\n    url: "https://oregonnews.uoregon.edu/lccn/sn00063700/1916-11-17/ed-1/"\n    type: "Primary newspaper page scans; visually verified 8/8 pages"\n    date: "1916-11-17"\n    repository_file: "evidence/source-captures/1916-enterprise-november17-visual-review-2026-09-13.md"\n    related_evidence: [E-335]\n'''; srcy.write_text(s)

evy=Path('database/evidence.yml'); s=evy.read_text()
for eid in ('E-333','E-334','E-335'):
    if f'  - id: {eid}' in s: raise SystemExit(f'{eid} already allocated YAML')
s += '''\n\n  - id: E-333\n    name: "3 November 1916 Enterprise complete visual review"\n    type: "Primary newspaper visual evidence / annual issue-level coverage"\n    claims: ["All 8/8 pages visually inspected.", "No source-explicit target-premises event; no-hit is bounded coverage only."]\n    confidence: "Very High"\n    related_sources: [S-360]\n    related_businesses: []\n    related_buildings: []\n    repository_file: "evidence/source-captures/1916-enterprise-november03-visual-review-2026-09-13.md"\n  - id: E-334\n    name: "10 November 1916 Enterprise complete visual review"\n    type: "Primary newspaper visual evidence / annual issue-level coverage"\n    claims: ["All 8/8 pages visually inspected.", "No source-explicit target-premises event; no-hit is bounded coverage only."]\n    confidence: "Very High"\n    related_sources: [S-361]\n    related_businesses: []\n    related_buildings: []\n    repository_file: "evidence/source-captures/1916-enterprise-november10-visual-review-2026-09-13.md"\n  - id: E-335\n    name: "17 November 1916 Enterprise complete visual review"\n    type: "Primary newspaper visual evidence / annual issue-level coverage"\n    claims: ["All 8/8 pages visually inspected.", "No source-explicit target-premises event; no-hit is bounded coverage only."]\n    confidence: "Very High"\n    related_sources: [S-362]\n    related_businesses: []\n    related_buildings: []\n    repository_file: "evidence/source-captures/1916-enterprise-november17-visual-review-2026-09-13.md"\n'''; evy.write_text(s)

cp=Path('evidence/source-captures/1916-online-audit-checkpoint.md'); s=cp.read_text()
for old,new in [('353/426 certified visually reviewed pages through 27 October 1916','377/426 certified visually reviewed pages through 17 November 1916'),('811 certified visually reviewed; 73 uncertified','835 certified visually reviewed; 49 uncertified'),('- Enterprise: **353/426 certified weekly pages**','- Enterprise: **377/426 certified weekly pages**'),('- Combined: **811/884 certified**','- Combined: **835/884 certified**'),('- Enterprise pages remaining uncertified: **73**','- Enterprise pages remaining uncertified: **49**'),('The next ordinary unreviewed Enterprise issue is **3 November 1916**.','The next ordinary unreviewed Enterprise issue is **24 November 1916**.')]:
    if old not in s: raise SystemExit(f'checkpoint expected text missing: {old}')
    s=s.replace(old,new,1)
s += '''\n\n## 13 September continuation — 3, 10, and 17 November certified\n\n- **3 November 1916:** 8/8 original weekly pages visually inspected (`S-360`, `E-333`); no source-explicit target-premises event.\n- **10 November 1916:** 8/8 original weekly pages visually inspected (`S-361`, `E-334`); no source-explicit target-premises event.\n- **17 November 1916:** 8/8 original weekly pages visually inspected (`S-362`, `E-335`); no source-explicit target-premises event.\n- Recurring non-target Main Street controls and printed transfer material were checked in all three issues without a source-explicit 501/503/505/505½/507 Main event.\n- Enterprise certified coverage is now **377/426**; combined newspaper coverage is **835/884**; **49 Enterprise pages remain uncertified**.\n- The true **12 May weekly page 8** remains a `RETRIEVAL GAP`.\n- Next ordinary Enterprise issue for visual review: **24 November 1916**.\n'''; cp.write_text(s)

ys=Path('registers/year-status.md'); s=ys.read_text()
for old,new in [('Enterprise **353/426 certified visually reviewed pages through 27 October 1916**','Enterprise **377/426 certified visually reviewed pages through 17 November 1916**'),('Combined certified newspaper coverage **811/884**; **73 Enterprise pages remain uncertified**.','Combined certified newspaper coverage **835/884**; **49 Enterprise pages remain uncertified**.'),('the next ordinary unreviewed issue is **3 November 1916**.','the next ordinary unreviewed issue is **24 November 1916**.')]:
    if old not in s: raise SystemExit(f'year-status expected text missing: {old}')
    s=s.replace(old,new,1)
marker='`evidence/source-captures/1916-enterprise-october27-visual-review-2026-09-13.md`'
addition=marker+'; `evidence/source-captures/1916-enterprise-november03-visual-review-2026-09-13.md`; `evidence/source-captures/1916-enterprise-november10-visual-review-2026-09-13.md`; `evidence/source-captures/1916-enterprise-november17-visual-review-2026-09-13.md`'
if addition not in s:
    if marker not in s: raise SystemExit('October27 marker missing')
    s=s.replace(marker,addition,1)
ys.write_text(s)
