#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def read(rel):
    return (ROOT / rel).read_text(encoding="utf-8")


def write(rel, text):
    (ROOT / rel).write_text(text, encoding="utf-8")


def append_once(rel, marker, block):
    text = read(rel)
    if marker in text:
        return
    write(rel, text.rstrip() + "\n\n" + block.rstrip() + "\n")


triage = '''# 1918–1920 Enterprise transition candidate triage — 31 August 2026

Status: **TARGETED OCR PASS TRIAGED; no new 503/505 construction notice recovered; one new Gilbert Miller OCR-only relocation lead retained**

## Scope

This closes the candidate review generated by `evidence/source-captures/1918-1920-505-transition-ocr-discovery.json` and the compact/context indexes. The discovery pass covered **91 Oregon City Enterprise issues / 728 OCR pages** from 1 October 1918 through 30 June 1920 and produced 18 candidate pages.

OCR remains discovery only under `RESEARCH-STANDARD.md`. This triage does not convert OCR into primary visual evidence and does not certify either 1919 or 1920 as ONLINE COMPLETE.

## Candidate disposition

| # | Date/page | Disposition |
|---:|---|---|
| 1 | 22 Nov 1918 p.6 | **Unrelated.** The Gilbert Miller hit is a military/casualty-list entry with emergency address William P. Miller, Rogerson, Idaho; not the target business chronology. |
| 2 | 14 Mar 1919 p.7 | **Unrelated.** Clem Dollar appears in a Justice of the Peace expense list; construction language occurs elsewhere on the page. |
| 3 | 25 Apr 1919 p.8 | **Unrelated.** Clem Dollar appears in court/justice expenses; move/lease wording is elsewhere and unrelated. |
| 4 | 13 Jun 1919 p.1 | **Unrelated to 505/construction.** Article concerns an old butcher debt dispute involving goods sold to Clem Dollar in 1915. |
| 5 | 4 Jul 1919 p.2 | **Unrelated.** Personal Willamette-area notice says Clem Dollar visited his sister; construction/move terms belong to other local/rural notices. |
| 6 | 11 Jul 1919 p.2 | **Unrelated.** Personal notice says Clem Dollar motored to Independence. |
| 7 | 11 Jul 1919 p.5 | **RETAIN AS OCR-ONLY IDENTITY/RELOCATION LEAD.** A marriage/local item says the bride was the eldest daughter of **Gilbert Miller, Ninth and Division streets**, and that she came to Oregon City about a year earlier with her parents from Springfield. This independently fits the 1918 Springfield→Oregon City chronology, but the scan has not yet been visually verified in this pass. Do not promote it to evidence or use it to resolve the C. E. Miller/Gilbert Miller conflict until the page image is inspected. |
| 8 | 18 Jul 1919 p.2 | **Unrelated.** Personal notice says Clem Dollar and Anna Dollar motored to Newberg; nearby construction language concerns other properties. |
| 9 | 1 Aug 1919 p.2 | **Unrelated.** Personal notice says Clem Dollar motored to Wilhoit; other move/property wording is separate. |
| 10 | 15 Aug 1919 p.2 | **Unrelated.** Dollar family picnic notice; other construction/move language is separate. |
| 11 | 22 Aug 1919 p.2 | **Unrelated.** Dollar family beach outing; a different family moved elsewhere. |
| 12 | 29 Aug 1919 p.2 | **Unrelated.** Dollar family returned from Netarts; no target address/building statement. |
| 13 | 12 Sep 1919 p.7 | **Unrelated.** Clem Dollar appears in a Justice of the Peace expense list. |
| 14 | 13 Feb 1920 p.5 | **Known and already visually verified** as `S-150` / `E-135`: Clem Dollar proprietor of a pool hall on Main between Fifth and Sixth. |
| 15 | 19 Mar 1920 p.7 | **OCR collision.** Gilbert Miller appears in a financial/list item; generic pool-room arrest and highway/construction language occur in separate articles. No target connection. |
| 16 | 16 Apr 1920 p.8 | **Business context only, not address/construction evidence.** A motorcycle event prize list says 50 cigars were supplied by Clem Dollar. No premises is identified. |
| 17 | 23 Apr 1920 p.1 | **Business context only, OCR-only.** Clem Dollar and Tom Smith are reported appointed county agents for the Stuart Puncture Proof Tire & Liner company and described as well-known Oregon City businessmen. No 505/505½ or pool-hall location is printed in the recovered context. |
| 18 | 4 Jun 1920 p.3 | **Known and already visually verified** as `S-150` / `E-135`: A. Leland's application to operate a pool hall at 505½ Main and erect an electric street sign was granted. |

## Construction result

After triage, **none of the 18 candidate pages supplies a new demolition, rebuilding, enlargement, remodel, lease-to-new-building, or construction notice for 501, 503, 505, or 505½ Main**. This is a bounded search result only. It is not evidence that no work occurred, especially because the 17 July 1919–1920 *Banner-Courier* run remains a material microfilm gap.

The strongest exact-number 1920 fact remains the visually verified 505½ pool-hall/sign approval (`E-135`). The physical-change date of the surviving 503/505 buildings remains unresolved.

## Forward path

1. Recover the **2 June 1920 Oregon City Council/Commission minutes** underlying the Leland approval.
2. Inspect the **1919–1920 R. L. Polk Oregon and Washington State Gazetteer and Business Directory** Oregon City section.
3. Inspect the **Banner-Courier** microfilm from 17 July 1919 through December 1920.
4. Retrieve 1919–1922 assessment/tax/deed/improvement records for original Block 4 Lots 3–4 and the Harding property chain.
5. Visually verify the 11 July 1919 Gilbert Miller family-relocation page if the identity chronology is pursued further.
'''
write("evidence/source-captures/1918-1920-505-transition-candidate-triage-2026-08-31.md", triage)

access = '''# 1919–1920 municipal and directory access trail — 31 August 2026

Status: **RETRIEVAL PATHS IDENTIFIED; target records not yet visually inspected**

This capture records exact access paths for the two highest-value online/retrieval targets after the focused Enterprise triage. It is retrieval documentation, not evidence of a construction event or occupancy.

## 2 June 1920 Oregon City Commission record

Oregon City's current **Meeting Document Archive** still explicitly lists **“1920 to 1929 City Commission Agenda Packets and Minutes.”**

Current City archive page:
https://www.orcity.org/1844/Meeting-Document-Archive

The 1920–1929 link currently points to the legacy Oregon Records Management Solution / HPRM WebDrawer query:

https://ormswd.synergydcs.com/HPRMWebDrawer/Record?q=webdrawercode%3A%22%2A023%2A%22+And+recTitle%3A%22%2A192%2A+city+commission%2A%22+And+recContainer%3A3AAgenda+Packets+and+Minutes&sortBy=recTypedTitle-

On 31 August 2026 that legacy target returned **404 Not Found** through the available web reader. This is a retrieval failure, not evidence that the June 1920 minutes do not exist.

The City's current **Public Records Self-Service Portal** states that Oregon City is transitioning to a new electronic records-management system, warns of access delays during the transition, and identifies **Laserfiche / E-Vault** as the current electronic archive route:

https://www.orcity.org/596/Public-Records-Self-Service-Portal

Therefore the exact **2 June 1920** meeting record remains a live migration/retrieval target. Highest-value text to inspect: A. Leland; 505½ Main; pool hall; electric street sign; owner/landlord; room/premises description; building work; permit/license references.

## 1919–1920 Polk statewide directory

OnGenealogy's Oregon directory index explicitly lists two FamilySearch image sets for **Oregon and Washington State Gazetteer and Business Directory, 1919–1920**:

Index page:
https://www.ongenealogy.com/listings/oregon-city-directories-online/

Part 1 FamilySearch starting image / catalog 1439422:
https://www.familysearch.org/ark:/61903/3:1:3QS7-89NM-NZJG?cat=1439422&mode=g

Part 2 FamilySearch starting image / catalog 1439422:
https://www.familysearch.org/ark:/61903/3:1:3QS7-L9NM-N6ZR?cat=1439422&mode=g

The available web reader reached both links but returned a FamilySearch cache/access failure rather than page images. Treat this as an authenticated-image retrieval task, not an absent directory.

A separate physical holding is cataloged by the **Stillaguamish Valley Genealogical Society** as:

- Call number **WA-120.1919**
- *Oregon and Washington State Gazetteer and Business Directory 1919-1920*
- R. L. Polk & Co.

Catalog evidence:
https://stillygen.org/libraryRecords.php?le=f3_c162&nr=50&page=96&scl=bda&srch=&st=T

## Directory inspection priorities

Once image access is available, inspect the Oregon City section and any business/classified indexes for:

- **501, 503, 505, and 505½ Main**;
- Wolf & Miller / Wolf / Miller;
- Gilbert Miller;
- Clem Dollar;
- A. Leland / Leland;
- Pantorium / cleaners / dyers / Phone 260 if telephone information is included;
- pool halls, billiards, cigars/tobacco, shoe repair, tailoring;
- Post Office and Fifth–Sixth Main relative-location clues.

Do not infer vacancy from an omitted listing and do not merge similarly named people without an independent bridge.
'''
write("evidence/source-captures/1919-1920-municipal-directory-access-trail-2026-08-31.md", access)

# Add a bounded closeout section immediately before the resume plan.
cp_rel = "evidence/source-captures/1919-1920-501-503-505-construction-checkpoint.md"
cp = read(cp_rel)
marker = "## 31 August 2026 targeted Enterprise triage closeout"
if marker not in cp:
    section = '''## 31 August 2026 targeted Enterprise triage closeout

A second focused *Enterprise* OCR pass covering **1 Oct 1918–30 Jun 1920** checked **91 issues / 728 pages** and produced 18 candidate pages. The candidate contexts have now been fully triaged in `evidence/source-captures/1918-1920-505-transition-candidate-triage-2026-08-31.md`.

Result: the two truly target-specific pages are the already visually verified **13 Feb 1920 Clem Dollar block-level pool hall** and **4 Jun 1920 A. Leland 505½ pool-hall/sign approval** (`E-135` / `S-150`). The remaining candidates are unrelated name/keyword collisions or general business context. No new 501/503/505 demolition/rebuild/remodel notice emerged from this bounded pass.

One non-construction OCR-only lead is retained: **11 Jul 1919 p.5** says a daughter of Gilbert Miller, then of Ninth and Division, came to Oregon City with her parents from Springfield about a year earlier. It is not promoted until visual scan review.

The municipal/directory retrieval path is now pinned in `evidence/source-captures/1919-1920-municipal-directory-access-trail-2026-08-31.md`: Oregon City's current archive still lists 1920–1929 Commission minutes but its legacy ORMS link returns 404 during the City's records-system transition; the 1919–1920 Polk directory is identified at FamilySearch catalog **1439422**, exact starting ARKs recorded for both parts, with a separate physical holding `WA-120.1919` at Stillaguamish Valley Genealogical Society.

'''
    anchor = "## Resume point\n"
    if anchor not in cp:
        raise RuntimeError("checkpoint resume anchor missing")
    cp = cp.replace(anchor, section + anchor, 1)
    write(cp_rel, cp)

# Append the triage result to the discovery capture for easy navigation.
append_once(
    "evidence/source-captures/1918-1920-505-transition-ocr-discovery.md",
    "## Candidate triage completed — 31 August 2026",
    '''## Candidate triage completed — 31 August 2026
All 18 candidate pages have now been context-triaged. See `evidence/source-captures/1918-1920-505-transition-candidate-triage-2026-08-31.md` and `evidence/source-captures/1918-1920-505-transition-target-context.md`.

No new 501/503/505 construction notice survived triage. The known 13 Feb and 4 Jun 1920 pool-hall anchors were rediscovered; the 11 Jul 1919 Gilbert Miller family-relocation wording is retained only as an OCR-only lead pending page-image review. Search silence is not evidence of absence.'''
)

append_once(
    "registers/research-log.md",
    "### 2026-08-31 — 1918–1920 Enterprise candidates triaged; municipal/directory access pinned",
    '''### 2026-08-31 — 1918–1920 Enterprise candidates triaged; municipal/directory access pinned
- Completed context triage of all 18 hits from the 91-issue / 728-page focused *Enterprise* transition search.
- No new 501/503/505 demolition, rebuild, enlargement or remodel notice survived triage. Known `E-135` pool-hall anchors remain the target-specific hits.
- Retained one OCR-only non-construction lead: 11 Jul 1919 p.5 places Gilbert Miller's family in Oregon City after a move from Springfield about a year earlier; visual verification still required.
- Recorded the exact legacy Oregon City 1920–1929 Commission WebDrawer query, its current 404 retrieval failure during the City's records-system transition, and current Laserfiche/E-Vault route.
- Recorded exact FamilySearch catalog 1439422 ARKs for both 1919–1920 Polk directory parts and physical holding `WA-120.1919` at Stillaguamish Valley Genealogical Society.
- No annual-completion status change and no new evidence/source IDs assigned from retrieval or OCR-only material.'''
)

print("Prepared 1918-1920 candidate triage and access-path integration")
